// Array con las 200 razones por las que la amo
const razones = [
    "Porque tu carisma, a veces sutil pero siempre presente, transforma cualquier momento en algo más cálido y especial.",
    "Porque tu empatía y amabilidad son como la luz de un faro, guiando e iluminando el camino de quienes te rodean.",
    "Porque tratas a los demás con una empatía genuina, siempre buscando ayudar a la mayor cantidad de personas posible.",
    "Porque tu curiosidad inagotable, aunque a veces imprudente, te impulsa a aprender con pasión siempre que algo capta tu atención.",
    "Porque tu carácter educado se manifiesta con sutileza, desbordando elegancia y gracia en cada gesto.",
    "Porque tu firmeza y determinación, cuando la situación lo exige, te hacen ver como alguien digno de respeto.",
    "Porque la madurez con la que actúas demuestra que, a pesar de tu juventud, sabes tomar decisiones con sabiduría.",
    "Porque la calidez de tu cuidado y protección se hace evidente con quienes te importan, siempre procurando su bienestar.",
    "Porque tu fortaleza imponente brilla cuando persigues algo que deseas de verdad, inspirando a quienes te rodean.",
    "Porque tu sonrisa, preciosa y radiante, ilumina todo a su alrededor como un pequeño sol en la Tierra.",
    "Porque el calor de tus abrazos es un refugio, transmitiendo amor y ternura cada vez que me envuelves en ellos.",
    "Porque cuando retrocedo y observo lo que hemos construido, todo se siente hermoso, armonioso y lleno de significado.",
    "Porque imaginarte con sueñito o dormida a cualquier hora del día es una de las cosas más tiernas y adorables.",
    "Porque desde hace un tiempo, son tus preciosas palabras las que me desean dulces sueños cada noche, y eso lo valoro enormemente.",
    "Porque tu lado tierno y caprichoso despierta en mí el deseo de regalarte el mundo entero.",
    "Porque la emoción y el sentimiento con los que vives cada cosa que te alegra o te entusiasma son contagiosos y maravillosos.",
    "Porque no solo eres cariñosa, sino también una compañera incondicional, brindando apoyo y fortaleza a quienes te rodean.",
    "Porque la hermosa esencia que irradias inspira en mí sentimientos tan bonitos que solo quiero devolvértelos una y otra vez.",
    "Porque la imagen de tu preciosa carita nunca abandona mi mente, sin importar la hora del día.",
    "Porque, aunque no seas naturalmente cariñosa, eliges dedicarme palabras bonitas, y eso las hace aún más especiales.",
    "Porque me permites quererte de una manera tan bonita y sincera, demostrando que no necesito verte o tocarte todos los días para que mi amor por ti siga creciendo.",
    "Porque es un regalo indescriptible sentirme querido por una mujer tan preciosa e increíble como tú.",
    "Porque desde que te tengo un poco más cerca, mi mundo se ha vuelto infinitamente más hermoso.",
    "Porque la simple idea de verte, aunque sea por un instante, llena mi día de felicidad.",
    "Porque te quiero más de lo que estas palabras pueden expresar, y eso me deja espacio para seguir sintiendo por ti cosas aún más hermosas.",
    "Porque ante mis ojos siempre luces hermosa, sin importar la ocasión, el maquillaje o el peinado; para mí, eres perfecta tal como eres.",
    "Porque la primera vez que pude decirte que te quiero, el mundo entero se hizo pequeño, y solo importábas tú.",
    "Porque cuando se trata de ti, todo lo demás desaparece; no hay nada ni nadie que pueda quitarte el lugar de mi prioridad.",
    "Porque cuando tus manos envuelven mi rostro, me haces sentir pequeño e indefenso, pero al mismo tiempo seguro y protegido.",
    "Porque tus bonitos gustos musicales no solo acompañan tu día a día, sino que también hacen el mío más especial.",
    "Porque demuestras una increíble fortaleza cuando se trata de ser una mujer trabajadora e incansable, siempre dando lo mejor de ti.",
    "Porque la sinceridad brilla en cada uno de tus gestos y expresiones, haciéndote incapaz de ser deshonesta.",
    "Porque tu independencia te define, y siempre sabes desenvolverte con seguridad cuando te toca liderar cualquier situación.",
    "Porque todavía me pongo nervioso al querer decirte algo bonito, y porque se me eriza la piel cada vez que tú haces lo mismo.",
    "Porque hay tantas cosas de ti dentro de mí, que sé que jamás podrás irte; de alguna manera, siempre estarás en mi mente y en mi corazón.",
    "Porque tu emoción y alegría se vuelven contagiosas en esos pequeños momentos de hiperactividad, llenando todo de luz.",
    "Porque no me importa llegar un poco tarde a casa si eso significa poder estar contigo aunque sea un momento más.",
    "Porque no puedo evitar sonreír y emocionarme cada vez que me envías algo lindo que hiciste para mí.",
    "Porque, por más bonitos y alegres que sean algunos lugares, siempre sé que lo serían aún más si estuvieras allí conmigo.",
    "Porque la emoción de esperar un mensaje tuyo se convierte en alegría pura cuando, después de un tiempo, finalmente lo recibo.",
    "Porque sé que aún no soy la mejor versión de mí mismo, pero me entusiasma trabajar para alcanzarla y que seas tú quien la disfrute.",
    "Porque tu calma tiene el poder de apaciguar hasta los rincones más caóticos de mi alma.",
    "Porque siempre tienes los planes más entretenidos, y nunca decepcionas a quienes tienen la suerte de acompañarte.",
    "Porque tu pequeña gran altura, lejos de ser una inseguridad, solo te hace brillar con aún más intensidad.",
    "Porque tu preciosa voz, tu hermoso vocabulario y tu sutil manera de expresarte hacen que cada conversación contigo sea especial.",
    "Porque tu cabello, largo y hermoso, fascina a cualquiera que tenga la suerte de admirarlo.",
    "Porque tu devoción y la forma en que vives tu fe te guían y fortalecen, llevándote siempre a buscar el bien y el equilibrio en todo lo que haces.",
    "Porque amo tu 'bipolaridad' intencionada, esa habilidad para alternar entre lo divertido, lo tierno, lo autoritario o lo maduro, según lo requiera cada situación.",
    "Porque tu risa, tan única y contagiosa, siempre logra alegrar a quienes tienen la suerte de estar cerca de ti.",
    "Porque tus labios y tus besos, llenos de cariño, dicen mucho más que mil palabras y me hacen perder la razón.",
    "Porque cuando hablas de algo que realmente amas, tu pasión te hace ver aún más bella e inspiradora.",
    "Porque tu comprensión y receptividad te convierten en un apoyo invaluable para quienes necesitan ser escuchados y aconsejados.",
    "Porque eres una hermana mayor que siempre vela por el bienestar de sus hermanas, guiándolas con amor y protección.",
    "Porque tu nombre, hermoso, poco común y original, tiene un encanto único que me entusiasma cada vez que lo escucho.",
    "Porque expresas tu cariño de manera genuina, sincera y constante, haciendo que siempre se sienta especial.",
    "Porque tu responsabilidad brilla en cada compromiso, ya sea académico, familiar o personal, demostrando que eres una persona en quien se puede confiar.",
    "Porque amo tu espontaneidad entusiasta y llena de energía, que hace mi vida mucho más interesante y emocionante.",
    "Porque admiro profundamente la manera en que gestionas tus emociones y comprendes las de los demás con tanta sensibilidad.",
    "Porque tu optimismo ante la adversidad siempre logra transmitirme un sentimiento hermoso de esperanza.",
    "Porque la fidelidad a tus valores y la fortaleza con la que te mantienes firme en lo que crees son cualidades que inspiran.",
    "Porque reflejas tu amor propio en el cuidado que te das a ti misma, recordándome siempre la importancia de valorarse.",
    "Porque tus ojos, profundos y enigmáticos como el mar, reflejan con sinceridad cada una de tus emociones.",
    "Porque tu estilo al vestir realza aún más tu belleza, haciéndote lucir espectacular con cualquier prenda.",
    "Porque tu aroma, dulce y distintivo, deja una huella inolvidable en cualquiera que tenga la suerte de acercarse a ti.",
    "Porque tus manos, pequeñas y preciosas, transmiten una combinación perfecta de elegancia y fuerza.",
    "Porque tus habilidades prácticas, como tu gran responsabilidad financiera, te permiten desenvolverte con independencia y seguridad.",
    "Porque tu capacidad de organización hace que administres con equilibrio cada aspecto de tu vida cotidiana.",
    "Porque tu habilidad para socializar te permite conectar tanto con quienes recién conoces como con aquellos con quienes ya tienes confianza.",
    "Porque tu actitud servicial y amable siempre está presente cuando alguien necesita ayuda, incluso si es solo con un consejo.",
    "Porque tus modales y tu educación te envuelven en un aura armoniosa de elegancia y distinción.",
    "Porque tu energía y vitalidad parecen inagotables, y cuando necesitas recargarlas, un sueño profundo es suficiente para devolvértelas.",
    "Porque la firmeza y seguridad con las que hablas inspiran confianza en todos los que tienen el privilegio de escucharte.",
    "Porque has tenido la disposición de crecer conmigo y construir juntos algo verdaderamente hermoso.",
    "Porque sabes apreciar hasta los más pequeños detalles, y esa sensibilidad te hace aún más especial.",
    "Porque tienes un instinto protector que me hace sentir seguro, sin caer en celos ni posesividad.",
    "Porque la confianza que me brindas nos permite edificar juntos los cimientos de una relación cada vez más fuerte.",
    "Porque la calidez de tus besitos rodeando mis mejillas es tan bonita que logra incluso desconcentrarme.",
    "Porque tu claridad y sinceridad nos permiten tener conversaciones afectivas sobre temas que podrían afectar nuestra relación, fortaleciendo aún más nuestro vínculo.",
    "Porque tienes la capacidad de dar y demostrar cariño sin esperar nada a cambio, simplemente porque nace de ti.",
    "Porque contigo descubrí la belleza de los silencios cómodos, esos momentos en los que no hacemos nada en particular, pero tu sola presencia lo hace especial.",
    "Porque el suave y cálido roce de tu nariz contra la mía es un gesto tan tierno que me llena de amor.",
    "Porque cuando me haces un cumplido o simplemente dices que me veo bien, me haces sentir más seguro de mí mismo.",
    "Porque, en lugar de perder interés con el tiempo, cada día hemos ganado más, fortaleciendo lo nuestro.",
    "Porque tu presencia es la mejor compañía, tanto en los momentos felices como en los más estresantes.",
    "Porque me inspiras a esforzarme más solo con verte trabajar con tanto empeño y dedicación.",
    "Porque no necesitas que nadie te presione para hacer lo correcto; sigues tu propia brújula ética y moral, siempre guiándote por el mejor camino.",
    "Porque eres increíblemente inteligente y no te dejas engañar fácilmente por nadie.",
    "Porque tienes una gran capacidad para desenvolverte en conversaciones amenas sobre una amplia variedad de temas.",
    "Porque, incluso cuando te equivocas, sabes que la vida es un proceso de aprendizaje y que, mientras sigas aprendiendo, nunca estarás fallando.",
    "Porque has sido paciente al darnos el tiempo necesario para aceptar nuestras diferencias y crecer juntos.",
    "Porque nuestras largas noches de charla, ya sea sobre temas triviales o para decirnos cosas bonitas, se han convertido en momentos inolvidables.",
    "Porque, a pesar de lo ocupada que estés, siempre haces el esfuerzo de encontrar espacios para que podamos estar juntos.",
    "Porque tu fortaleza me inspira a levantarme cada día y trabajar por un futuro mejor.",
    "Porque eres una excelente conversadora, pero también sabes escuchar con atención y dar espacio a los demás para expresarse.",
    "Porque tu sentido del orden te hace querer que todo esté en su lugar, reflejando tu armonía y equilibrio.",
    "Porque caminar contigo por la calle, tomados de la mano, convierte cualquier trayecto en algo especial.",
    "Porque siempre buscamos la manera de compartir momentos de calidad, sin importar lo ocupados que estemos.",
    "Porque cuando te abrazo y quedo a la altura de tu pecho, sentir los latidos de tu corazón me llena de paz.",
    "Porque, incluso después de un tiempo sin verte, sigo poniéndome nervioso y emocionado al verte de nuevo.",
    "Porque la dedicación y el amor con los que cuidas de tu hogar y tu familia reflejan lo hermosa que eres por dentro y por fuera.",
    "Porque el precioso peluche que me regalaste es un recordatorio de ti y me hace compañía cada noche.",
    "Porque siempre deseas lo mejor para mí, demostrando cuánto te importa mi felicidad y bienestar.",
    "Porque cada vez que me llamabas para que fuera hasta donde estabas, me llenaba de emoción solo con escuchar tu voz.",
    "Porque me permites acariciar tu rostro con delicadeza, disfrutando la suavidad de tu piel entre mis manos.",
    "Porque me dejas demostrar mi lado caballeroso cuando salimos juntos, haciéndome sentir especial a tu lado.",
    "Porque eres lo primero en lo que pienso al despertar y lo último antes de dormir, llenando mis días de amor.",
    "Porque contigo siento la confianza y seguridad de poder hablar de cualquier cosa sin temor a ser juzgado.",
    "Porque estar a tu lado me hace sentir una mejor persona y me inspira a seguir creciendo.",
    "Porque siempre me das espacio para hablar de lo que me apasiona y te entusiasmas, aunque no lo entiendas del todo.",
    "Porque adoro pasar horas contigo, incluso cuando estamos lejos y solo podemos compartir a través de una pantalla.",
    "Porque puedo perderme en el brillo de tus preciosos ojos, disfrutando de silencios cómodos y llenos de significado.",
    "Porque en mí despiertas sentimientos de amor y ternura que antes ni siquiera sabía que existían.",
    "Porque, sin importar dónde esté, si estoy contigo, me siento en casa.",
    "Porque cuando me besas, el mundo entero desaparece y solo existimos tú y yo.",
    "Porque, incluso en los lugares más cómodos y felices, siempre pienso que sería aún mejor si estuvieras a mi lado.",
    "Porque me permites cuidarte y estar pendiente de ti cuando no te sientes bien, confiando en mi cariño.",
    "Porque cuando estoy contigo me siento vulnerable, no por debilidad, sino porque has entrado en mi vida de una manera única y especial.",
    "Porque me inspiras a mejorar en todos los aspectos, desde cómo me visto hasta cómo me cuido. Quiero ser lo mejor para ti, y gracias a ti he cambiado para bien.",
    "Porque me orientas a tomar decisiones con claridad y me apoyas incondicionalmente cuando las tomo.",
    "Porque la armoniosa simetría de tu rostro es un reflejo de tu belleza, donde cada detalle—tus ojos, tu nariz, tus labios—parece estar en perfecta sintonía.",
    "Porque gracias a ti he descubierto nuevas formas de expresarme y he conocido personas maravillosas que han enriquecido mi vida.",
    "Porque me das la libertad de ser dramático a veces, sabiendo que contigo puedo ser completamente yo.",
    "Porque, aunque aún eres joven, tienes la madurez y la responsabilidad que muchos adultos desearían tener.",
    "Porque cuando estoy contigo, el tiempo se vuelve efímero, y cada instante parece pasar demasiado rápido.",
    "Porque adoro tus ataques de amor en la madrugada, cuando me escribes cosas hermosas y me haces sentir como un niño chiquito y querido.",
    "Porque muestras un interés genuino por las cosas que son importantes para mí, al punto de hacerlas parte de tu mundo también.",
    "Porque, aunque a veces me cueste expresar lo que siento, mis sentimientos por ti son tan fuertes que me inspiran a escribirlos.",
    "Porque me haces sentir una necesidad inmensa de abrazarte y acariciar tu largo cabello durante horas.",
    "Porque no puedo evitar sonreír cada vez que hablo o escribo sobre ti.",
    "Porque cuando estoy contigo, el mundo a mi alrededor simplemente desaparece.",
    "Porque cuando estoy triste o desanimado, pasar un rato contigo me devuelve la alegría y las ganas de seguir adelante.",
    "Porque te preocupas no solo por mí, sino también por mi familia, aunque los conozcas poco.",
    "Porque en ti encontré un refugio seguro, incluso para mostrar mi tristeza sin miedo, hasta el punto de llorar.",
    "Porque aunque a veces tu perfume me embriague, cuando no estás cerca lo extraño más de lo que imaginaba.",
    "Porque lograste caerles bien de inmediato a los muchachos que son como mis hermanos, como si siempre hubieras sido parte de nuestras vidas.",
    "Porque me aguantas con paciencia y, de alguna manera, asumes el papel de la persona madura cuando yo no lo soy.",
    "Porque te ves preciosa con las camisetas que te he regalado (aunque, en realidad, todo te queda bien).",
    "Porque nuestra curiosa rutina de recordarnos mutuamente lo que el otro debía recordar siempre me saca una sonrisa.",
    "Porque tus antojos raros, curiosos y espontáneos en medio de la noche, sin importar la hora, me parecen adorables.",
    "Porque eres de las pocas personas que lograron causar una excelente impresión en mi madre con tan solo una pequeña charla.",
    "Porque me encanta escucharte hablar de cualquier cosa, incluso cuando lo haces sin parar.",
    "Porque la calidez de tus pequeñas y bonitas manos entrelazadas con las mías me da una paz inexplicable.",
    "Porque en ti y en tu pequeño cuerpecito encuentro la combinación perfecta de fuerza imponente y ternura infinita.",
    "Porque inventamos excusas evidentes solo para poder vernos más seguido, y eso me hace feliz.",
    "Porque tu energía extrovertida me impulsa a salir de casa y recorrer el mundo a tu lado.",
    "Porque siempre te acuerdas de las pequeñas cosas que me desagradan, como el huevo o la Coca-Cola, y cuidas de que no me molesten.",
    "Porque, aunque quieres quedarte hablando conmigo un ratito más, tu cuerpo siempre termina rindiéndose al sueñito.",
    "Porque me has invitado a tu iglesia con cariño, impulsándome e inspirándome a aprender sobre algo tan importante para ti.",
    "Porque aquel día me besaste sin dudarlo, aun sabiendo que corrías el riesgo de contagiarte de mi gripe.",
    "Porque las curvas armónicas y precisas de tu cuerpo reflejan un atractivo inigualable, que hipnotiza sin esfuerzo.",
    "Porque luces increíblemente tierna cuando estamos estudiando y, con una sonrisa cómplice, dices: 'tomémonos un descanso'.",
    "Porque no intentas cambiarme, sino que me aprecias y demuestras que me quieres tal como soy.",
    "Porque el tono de tu piel parece esculpido con la esencia misma de la perfección.",
    "Porque confías en mí lo suficiente para compartir aspectos íntimos de tu vida, y eso es un regalo invaluable.",
    "Porque me hipnotiza ver tus labios moverse cuando hablas y enamorarme aún más cuando se curvan en una sonrisa.",
    "Porque siempre te emocionas al escuchar los chismes que te cuento, aunque yo no sea el mejor narrador.",
    "Porque tu cabello siempre luce increíble, sin importar cómo lo lleves.",
    "Porque nuestros 'ratos pequeños' juntos siempre terminan convirtiéndose en largas horas de complicidad.",
    "Porque la forma de tu barbilla y mandíbula es simplemente encantadora.",
    "Porque ese par de cicatrices en tu piel son pequeñas huellas de tu historia, recuerdos de un pasado que te hace ser tú.",
    "Porque me haces sentir visto y apreciado en un mundo que a veces parece ignorarme.",
    "Porque puedes entender lo que quiero decir sin necesidad de demasiadas palabras.",
    "Porque siempre tienes una teoría alocada pero encantadora para justificar cualquier cosa.",
    "Porque contigo encuentro la seguridad y confianza para hablar de mis miedos y debilidades sin temor a ser juzgado.",
    "Porque me escuchas con atención, incluso cuando no tengo mucho o algo particularmente interesante que decir.",
    "Porque la forma en que parpadeas lentamente cuando dices que 'estás lista' y tienes sueño es simplemente adorable.",
    "Porque cada vez que veo algo bonito en la calle, no puedo evitar imaginar lo feliz que te haría recibirlo.",
    "Porque sabes respetar las decisiones de los demás, incluso cuando no las compartes.",
    "Porque permites que los sentimientos surjan y crezcan sin minimizarlos ni hacerlos sentir insignificantes.",
    "Porque, de alguna manera, siempre estás presente en mi mente, incluso cuando no pienso directamente en ti.",
    "Porque contigo, los miedos se vuelven más pequeños y la confianza crece sin límites.",
    "Porque tus palabras tienen el poder de calmarme y hacerme sentir seguro, sin importar lo que pase.",
    "Porque la manera en que frunces el ceño cuando intentas recordar algo es increíblemente tierna.",
    "Porque, aunque hay ciertos días en los que te sientes más sensible, siempre encuentras la forma de seguir adelante con fortaleza.",
    "Porque la perfección de tus dientes hace que tu sonrisa sea aún más deslumbrante.",
    "Porque no solo me diste tu cariño y afecto, sino que me abriste las puertas de tu mundo y me hiciste parte de él.",
    "Porque siempre priorizas el respeto y la admiración por encima de los celos o cualquier sentimiento posesivo.",
    "Porque cada beso tuyo sigue emocionándome como si fuera el primero.",
    "Porque resaltas en mí cualidades que nunca supe que tenía hasta que llegaste a mi vida.",
    "Porque la gracia natural con la que se mueven tus caderas y la firmeza con la que sostienes tu propio peso al caminar me hipnotizan.",
    "Porque ante cualquier incomodidad, nunca buscamos un 'ganador', sino que siempre abrimos un espacio para dialogar y entendernos mejor.",
    "Porque tus brazos se han convertido en un refugio perfecto cuando necesito un abrazo.",
    "Porque cada momento que decides pasar conmigo se siente como una elección hermosa y no como una simple rutina.",
    "Porque no temes mostrarme tus vulnerabilidades, y eso solo me acerca más a ti.",
    "Porque la forma en que tu clavícula se dibuja sobre tu piel tiene una elegancia que me fascina.",
    "Porque contigo encontré un amor que no busca poseer ni controlar, sino simplemente compartir y crecer juntos.",
    "Porque me inspiras a recordarte constantemente lo muchísimo que te quiero, aunque a veces pueda sonar repetitivo.",
    "Porque las líneas de tu cuello transmiten una elegancia natural que me cautiva.",
    "Porque me enseñaste a ver la belleza en esas películas que alguna vez creí 'solo para niños'.",
    "Porque la manera en que te despeinas sin darte cuenta es de una ternura irresistible.",
    "Porque quererte no es un esfuerzo agotador, sino una ligereza que llena mi vida de alegría.",
    "Porque, aunque a veces dude de si lo estoy haciendo bien, tú me haces sentir seguro en la manera en que te muestro mi afecto.",
    "Porque, por más complicados que sean los planes, mi mente siempre los simplifica con tal de verte un ratito.",
    "Porque cada parte de ti, por pequeña que sea, me parece hermosa y perfecta en su esencia.",
    "Porque me tienes amando cada precioso pedacito de lo que eres, y aun así, siempre descubro algo nuevo que me maravilla.",
    "Porque tan solo el hecho de saber que existes y que formas parte de mi vida llena mi corazón de una alegría indescriptible, como si el mundo entero me hubiera dado un regalo que jamás creí merecer.",
    "Porque cada vez que mis brazos te rodean, siento que han encontrado su hogar, un refugio donde mi cuerpo reconoce el tuyo, encajando perfectamente en el calor de tu piel, en la suavidad de tu respiración, en el latido pausado de tu corazón.",
    "Porque contigo aprendí que el amor no solo es un torbellino de emociones, sino la elección constante de cuidar, respetar y honrar lo que hemos construido, de sostenernos incluso en la incertidumbre, de dar sin esperar, de entregarnos con alma y cuerpo.",
    "Porque en ti descubrí sentimientos tan profundos e inmensos que a veces me asustan por su intensidad, pero al mismo tiempo me dan paz, porque sé que lo que siento por ti es real, puro y hermoso, algo que trasciende cualquier otra emoción que haya conocido.",
    "Porque en la luz de tus ojos veo reflejado el amor más puro, el amor que viene de lo divino, ese que no se impone, sino que se entrega, ese que no solo se siente, sino que transforma. Porque a través de ti he comprendido que el amor más bello es aquel que nos acerca a nuestra mejor versión."
];
